version: "3.7"
services:

  # nginx:
  #   container_name: nginx
  #   image: nginx:latest
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - api

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data

  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - REDIS_HOSTNAME=redis
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis
  